### ISSUE TITLE
Enabler: Use shared code NuGet packages.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#149]
# Use shared code from NuGet packages instead of copying code files.

The glossary API currently uses two projects (`NCI.OCPL.Api.Common` and `NCI.OCPL.Api.Common.Testing`) which have been copied and pasted from previous APIs. This means that fixes in one API aren't reflected in others and the so-called "common" code isn't.

The goal then is to remove those two projects and load NuGet packages from 

> **ESTIMATE** TBD

### Prerequisites
- [x] [NCI.OCPL.Api.Shared] Publish NuGet packages  - Issue  [#8](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/8)
- [x] [NCI.OCPL.Api.Shared] Make NuGet packages reference Elasticsearch 5.6  - Issue  [#10](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/10)

### Sub-Tasks
- [x] [Allow shared code to be debugged](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/18)
- [x] [Modify `CreateWebHostBuilder` to return `IHostBuilder`](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/19)
- [x] [Remove the shared DefaultController class](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/21)
- [x] [Move InterfaceArrayJsonConverter<T> to common code](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/22)
- [x] [Enable Newtonsoft.Json serialization](https://github.com/NCIOCPL/NCI.OCPL.Api.Shared/issues/25)
