### ISSUE TITLE
Switch the API to using v7.9.x of the NEST client

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#151]
Upgrade the NEST client to the 7.9.x version.

**Parent Issue:** #147

### Sub-Tasks
- [ ] Change the client version.
- [ ] Remove Elasticsearch document type from queries.
- [ ] Update unit tests to reflect the updated queries
