### ISSUE TITLE
Update Integration tests to use ES 7.9

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-api#152]
Switch the integration tests to use Elasticsearch 7.9

**Parent Issue:** #147

### Sub-Tasks
- [ ] Update the docker-compose.yml to specify Elasticsearch 7.9.2
- [ ] Update the index mapping file.
- [ ] Remove Elasticsearch document type from the test data.
- [ ] Update tests if needed.  (Should remain unchanged.)

### Notes

For `docker-compose.yml`
```
        image: elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
```
